language: node_js
node_js:
  - "5.5.0"
services:
  - mongodb
before_install:
  - npm install -g grunt-cli
install:
  - npm install
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./node_modules/protractor/bin/webdriver-manager update --standalone
  - npm run start-test &
  - sleep 5
script:
  - grunt protractor_webdriver
  - node_modules/.bin/protractor test/e2e/conf.js --browser=firefox
  - npm run test-jasmine
  - grunt karma
